### ISSUE TITLE
Problem in login credentials

### ISSUE THREAD

**Issue by SagarikaPatro** [linkeshkanna/SecurityTestAutomation#1]
I ran the program. It opened up a pop up from "Websense triton content gateway" asking for user name and PASSWORD.

I tried with all possible combinations. for eg:
1) domain username and password
2)admin -admin.

Nothing worked.
![websense](https://cloud.githubusercontent.com/assets/13161801/8493962/c85d9b22-217d-11e5-9761-25c5a987b3c4.PNG)

Can you provide us any solution for the above issue?

**Comment by linkeshkanna** [comment]
It not related to ZAP. Its a web security configured by your system admins. Please contact your system administrators or try it from your home.
